# -*- coding: utf-8 -*-
"""Project: 7 Password Generator Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HX3LFJeXFbR32S7nVko2IIpSzJjHuuXR
"""

import random
import string

def generate_password (length=12):
   characters = string.ascii_letters + string.digits + string.punctuation


   password = ' '.join(random.choice(characters) for _ in range(length))

   return password

try:
   length = int(input("Enter the length of the password(default is 12): ") or 12)


   if length < 8:
    print("Password length should be at least 8 characters. Setting length to 8.")


    length = 8

    password = generate_password(length)
    print("Genrated Password:")
    print(password)


except ValueError:
    print("Invalid input! Please enter a valid number.")